/**
 * The English handgrip script, line by line, as approved by András on 2026-10-04.
 *
 * Translated from the Hungarian take (IMG_1155) and used for the English voice. Each
 * entry is [seconds into the session, line]. Generated from
 * BeepIT-overlays/handgrip-en/tts-test/script-full.json (raw clock minus the 2.42 s
 * session offset), so regenerate rather than hand-edit if the script changes.
 */
export const HANDGRIP_SCRIPT_EN: [number, string][] = [
  [1.53, "Hi everyone, welcome! Today I'm going to show you a simple exercise with a hand gripper, and we'll do it together."],
  [10.39, "It can help bring your blood pressure down. The whole session takes just 12 minutes, from start to finish."],
  [17.77, "Of course, you can skip ahead if you like, so you don't have to listen to the whole 12 minutes and the explanation every time."],
  [24.77, "For this you'll need a hand gripper like this one. You can buy one in any fitness shop. This one has adjustable strength: you set how hard it is by moving the position of the spring, here."],
  [41.23, "According to clinical research, if you do this at least three times a week, your blood pressure can drop measurably after a few weeks."],
  [49.85, "Of course, that doesn't mean everyone will see their blood pressure come down. This is just an extra, something you add to look after your health."],
  [60.25, "If your blood pressure is very high, or not yet under control, be sure to talk to your doctor. In fact, I always suggest talking to your doctor before any exercise."],
  [70.71, "If you feel dizzy, or your chest or head hurts, please stop straight away."],
  [75.32, "And most importantly, keep breathing calmly the whole time. We'll do this squeeze twice on each arm, so four squeezes in total."],
  [87.67, "Sit comfortably, with your back straight and your feet on the floor. Rest the other arm on your thigh. For the working arm, keep 90 degrees between your upper arm and forearm, and 90 degrees to your body."],
  [104.71, "You don't need to squeeze it all the way; about halfway is enough. Don't pump it. About a third of your strength is plenty, and I'll say more about that during the exercise."],
  [117.25, "Let's start the exercise, with the right hand."],
  [120.78, "Now. I've squeezed it, and we'll hold it for two minutes."],
  [129.33, "It's important to breathe calmly, as we discussed. Now I'll tell you a little about how to set the strength."],
  [139.61, "There are basically two ways to do it. One is to measure your maximum grip strength with a grip meter, take 30 percent of that, and set this little gripper to it."],
  [157.23, "The other way is to try it setting by setting and see how much you can manage: whether you can do two holds of two minutes without it being very, very hard."],
  [177.91, "It's normal for this to be hard. Your hand will shake, and so on. But if it's unbearable, it means the gripper is set too strong, so that's what you need to adjust."],
  [191.91, "Only 45 seconds left on this side. Keep squeezing. You can see my hand and arm are shaking a little. That's fine, we'll see it through."],
  [202.91, "And that's exactly the point of these videos: they aren't edited. You see how I do it from start to finish, uncut, with every mistake and every imperfection. This video is exactly as it is, uncut."],
  [221.06, "20 seconds left. Keep squeezing."],
  [228.9, "Just 10 seconds now. Let's hang on together."],
  [240.3, "Great, let go. Take a deep breath, and shake out your right arm."],
  [245.96, "Move your hands around a little, take a few more deep breaths, and slowly get ready for the other side. Settle in comfortably on your seat again, back straight, 90 degrees between your upper arm and forearm,"],
  [267.66, "and we squeeze, now."],
  [277.12, "Breathe calmly, don't hold your breath."],
  [292.14, "You can see it's shaking, but that's fine."],
  [314.02, "If it shakes, hang in there. I hope you're managing. Squeeze it about halfway, and hold the gripper there."],
  [330.04, "Just one minute left. We're past halfway."],
  [357.92, "Only half a minute left. We'll get through it together. Come on, keep squeezing."],
  [380.42, "Great, 10 seconds left. Keep squeezing,"],
  [388.68, "and you can let go."],
  [394.48, "Move it around. Deep breaths."],
  [405.9, "And let's get ready for the right hand."],
  [415.17, "Feet on the floor."],
  [419.79, "Go."],
  [421.79, "The second round may feel a bit harder than the first. That's completely normal. Try to hold the gripper halfway, just like before."],
  [434.49, "And as we said, it's important to make this a routine. Try to do this exercise at least three times a week."],
  [447.22, "You need to keep doing it for several weeks before you feel the effect. And unfortunately, when you stop, the benefit goes away too. That's why it's important to make it a routine."],
  [480.04, "Great, just one minute left. We'll get through this."],
  [485.88, "Keep squeezing. You can see my right arm and hand are shaking now."],
  [499.98, "This is an isometric exercise. Isometric exercises like this can be really good for your blood pressure, but you have to do them regularly."],
  [517.5, "Just 20 seconds left. We'll get through it together. Come on, let's do it, squeeze."],
  [532.62, "My right arm is shaking quite a bit. That's OK. Hang on a little longer,"],
  [539.62, "and release. Great. Very good."],
  [546.63, "Move your arms and hands around. A few deep breaths. And get ready for the next one, the last squeeze."],
  [569.88, "Go. Squeeze."],
  [574.84, "About halfway, like before."],
  [579.68, "My left arm is weaker, so you can see it's shaking more, right from the start."],
  [621.76, "Hopefully you're managing."],
  [627.78, "We're halfway now, so just one minute left. We'll manage that. Come on, let's do it. Keep squeezing."],
  [650.52, "Breathe calmly."],
  [658.72, "Just half a minute left, and we'll see it through. Come on, squeeze."],
  [675.76, "15 seconds left."],
  [688.68, "And great, we can let go."],
  [693.42, "Well, the left hand wasn't easy by the end. Really nice work. Thank you so much for taking part."],
  [700.21, "As I said, it's important to make this a routine. Try to do it at least three times a week, at home or wherever you are. It's easy to do anywhere; just take your little gripper with you."],
  [713.21, "You'll feel the effect after about 3 to 4 weeks. And if you stop, it goes away. As I said, this is an extra routine to support your health."],
  [728.21, "Thanks again for joining me. Check out my other videos in the library too, isometric or other workouts. Thank you, bye!"],
]
